
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leo
 */
public class Cuadrado extends javax.swing.JPanel implements Runnable {
   Thread hilo2;
    int x=320;
    public Cuadrado() {
        initComponents();
        hilo2=new Thread(this);
    }

    
    
     public void paint(Graphics sd){
        sd.setColor(Color.DARK_GRAY);
        sd.fillRect(0, 0, getWidth(), getHeight());
        sd.setColor(Color.red);
        sd.fillRect(x, 0, 20, 20);
        
    }
     public void iniciar(int r){
         this.x=r;
         hilo2.start();
       }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       try {
        while(true){
            while(x<getWidth()-30){
               Thread.sleep(50);
                x-=10;
                repaint();
            }
            while(x>10){
                Thread.sleep(1000);
                x-=10;
                repaint();
            } 
            }
           } catch (Exception e) {
                   
                }
        }
    
}
